#!/bin/bash
echo "PAGE: total 1024" 1>&2
CURRENT_PDF="${1}"
TARGET_PDF=`echo ${CURRENT_PDF} | grep -o -P ".*/job_\d+" | sed -n "1p"`
mv ${CURRENT_PDF} ${TARGET_PDF}.pdf
/usr/local/bin/zbyprinting-analysis ${TARGET_PDF}
